//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShoppingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobilePhoneData
    {
        public int DeviceNumer { get; set; }
        public string DeviceName { get; set; }
        public string Brand { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
    }
}
